"""
DCAP TDX quote parser — Phase 7 (partial).

Overview
--------
Intel DCAP (Data Center Attestation Primitives) quotes are the production
attestation format for TDX (Trust Domain Extensions) VMs.  A full DCAP
verification pipeline involves:

  1. Parsing the binary quote structure (this file).
  2. Verifying the QE (Quoting Enclave) signature over the TD report.
  3. Walking the Intel PKI certificate chain (Root CA → Platform CA → QE cert).
  4. Checking CRL revocation status for each certificate.
  5. Matching FMSPC + TCB info against Intel's TCB Recovery service.
  6. Optionally verifying on-chain via a deployed DCAP verifier contract.

This module implements Step 1 only — quote structure parsing.  Steps 2–6 are
Phase 7 and require either an Intel DCAP library (PCCS) or an on-chain verifier
contract.  The partial output is still highly useful for a pitch: it proves the
quote is well-formed, identifies the TEE type, and binds the deal terms hash
back to the attestation.

TDX Quote Header Layout (48 bytes)
------------------------------------
Offset  Size  Field
------  ----  -----
0       2     version          (LE uint16; DCAP v4 = 4)
2       2     att_key_type     (LE uint16; ECDSA-P256 = 2)
4       4     tee_type         (LE uint32; TDX = 0x00000081, SGX = 0x00000000)
8       2     reserved1
10      2     reserved2
12      16    qe_vendor_id     (UUID bytes; Intel QE = 939A7233-F79C-4CA9-940A-0DB3957F0607)
28      20    user_data        (first 16 bytes = SHA-256 prefix of QE auth+cert data)

Total header: 48 bytes.

TD Report Body (starts at byte 48 inside the quote)
-----------------------------------------------------
The TD Report contains TEEINFO.  Within TEEINFO, the report_data field (64 bytes)
starts at offset 400 within TEEINFO (offset 448 from the start of the quote).
In DealProof, the first 32 bytes of report_data = SHA-256(json(deal_terms)).
The remaining 32 bytes are zero-padded.

Simulation mode
---------------
When TEE_MODE=simulation the attestation string is:
  "sim_quote:<sha256_hex>"
where the hex is the SHA-256 of the signed payload dict (deal terms + data_hash).
No binary parsing is performed in this mode.

Reference
---------
Intel TDX DCAP Quote Generation Library:
https://github.com/intel/SGXDataCenterAttestationPrimitives
"""
import struct
import logging

logger = logging.getLogger(__name__)

# Intel QE vendor UUID bytes (big-endian) — used to confirm the quote was
# generated by an Intel Quoting Enclave rather than a third-party QE.
_INTEL_QE_VENDOR_UUID = bytes.fromhex("939a7233f79c4ca9940a0db3957f0607")

# TEE type → human-readable string
_TEE_TYPES: dict[int, str] = {
    0x00000000: "SGX",
    0x00000081: "TDX",
}

# Known DCAP quote versions
_KNOWN_VERSIONS = {4}

# Byte offsets within the raw TDX quote
_HEADER_SIZE = 48
_TEEINFO_OFFSET = _HEADER_SIZE          # TD Report starts right after the header
_REPORT_DATA_OFFSET_IN_TEEINFO = 400    # report_data is 400 bytes into TEEINFO
_REPORT_DATA_OFFSET = _TEEINFO_OFFSET + _REPORT_DATA_OFFSET_IN_TEEINFO
_REPORT_DATA_LENGTH = 64                # 64 bytes total; first 32 = deal terms hash


def parse_tdx_quote(attestation: str) -> dict:
    """
    Parse a DealProof attestation string and return a dict matching the
    DCAPVerification schema fields (excluding deal_id).

    Parameters
    ----------
    attestation : str
        Either:
        - "sim_quote:<hex>" — simulation mode attestation
        - A hex-encoded binary TDX DCAP quote

    Returns
    -------
    dict with keys: mode, version, tee_type, qe_vendor_id, report_data_hex,
                    deal_terms_hash, verification_status, error
    """
    # ------------------------------------------------------------------ #
    # Simulation mode
    # ------------------------------------------------------------------ #
    if attestation.startswith("sim_quote:"):
        sim_hash = attestation[len("sim_quote:"):]
        return {
            "mode": "simulation",
            "version": None,
            "tee_type": None,
            "qe_vendor_id": None,
            "report_data_hex": sim_hash if len(sim_hash) == 64 else None,
            "deal_terms_hash": sim_hash if len(sim_hash) == 64 else None,
            "verification_status": "simulation_only",
            "error": None,
        }

    # ------------------------------------------------------------------ #
    # Production: attempt to hex-decode and parse
    # ------------------------------------------------------------------ #
    try:
        quote_bytes = bytes.fromhex(attestation)
    except ValueError as exc:
        return _error_result(f"attestation is not valid hex: {exc}")

    if len(quote_bytes) < _HEADER_SIZE:
        return _error_result(
            f"quote too short: {len(quote_bytes)} bytes (need at least {_HEADER_SIZE})"
        )

    # Parse header fields
    try:
        version, att_key_type = struct.unpack_from("<HH", quote_bytes, 0)
        (tee_type_raw,) = struct.unpack_from("<I", quote_bytes, 4)
        qe_vendor_id_bytes = quote_bytes[12:28]
    except struct.error as exc:
        return _error_result(f"header parse error: {exc}")

    tee_type_str = _TEE_TYPES.get(tee_type_raw, f"unknown(0x{tee_type_raw:08x})")
    qe_vendor_id_hex = qe_vendor_id_bytes.hex()
    is_intel_qe = qe_vendor_id_bytes == _INTEL_QE_VENDOR_UUID

    # Parse report_data (deal terms hash) if the quote is long enough
    report_data_hex: str | None = None
    deal_terms_hash: str | None = None
    if len(quote_bytes) >= _REPORT_DATA_OFFSET + 32:
        report_data_hex = quote_bytes[
            _REPORT_DATA_OFFSET: _REPORT_DATA_OFFSET + _REPORT_DATA_LENGTH
        ].hex()
        # First 32 bytes = SHA-256 of the deal terms payload
        deal_terms_hash = quote_bytes[_REPORT_DATA_OFFSET: _REPORT_DATA_OFFSET + 32].hex()
    else:
        logger.debug(
            "Quote too short for report_data extraction "
            f"(have {len(quote_bytes)} bytes, need {_REPORT_DATA_OFFSET + 32})"
        )

    logger.info(
        f"DCAP quote parsed: version={version}, tee_type={tee_type_str}, "
        f"intel_qe={is_intel_qe}, deal_terms_hash={deal_terms_hash}"
    )

    return {
        "mode": "production",
        "version": version,
        "tee_type": tee_type_str,
        "qe_vendor_id": qe_vendor_id_hex,
        "report_data_hex": report_data_hex,
        "deal_terms_hash": deal_terms_hash,
        "verification_status": "dcap_header_parsed",
        "error": None,
    }


def _error_result(error: str) -> dict:
    """Return a DCAPVerification-compatible dict for an unrecoverable parse error."""
    logger.warning(f"DCAP parse failed: {error}")
    return {
        "mode": "unknown",
        "version": None,
        "tee_type": None,
        "qe_vendor_id": None,
        "report_data_hex": None,
        "deal_terms_hash": None,
        "verification_status": "invalid_quote",
        "error": error,
    }
